name: first workFlows 

on:
   push:
      branches:
        - main

jobs:
  example-jop:
    runs-on: ubuntu-latest

    steps:
      - name: print a welcome message
        run: echo "welcome to our first Github Actions workflow"
