name: first workflows

on:
  push:
    branches:
      - main

jobs:
  example-job:
    runs-on: ubuntu-latest

    steps:
      - name: print a welcome message
        run: echo "welcome to our first Github Actions workflow"

      - name: checkout repository
        uses: actions/checkout@v4

      - name: list repository files
        run: ls -la
        
